"""
Deep Q-Network (DQN) Agent for Health Coaching
Uses Random Forest-extracted conditions as state features
"""

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import deque
import random
from typing import List, Tuple
import pandas as pd


class DQNNetwork(nn.Module):
    """
    Neural network for Q-value approximation
    Input: Condition features from Random Forest
    Output: Q-values for each action
    """
    
    def __init__(self, state_dim: int, action_dim: int, hidden_dims: List[int] = [256, 128, 64]):
        super(DQNNetwork, self).__init__()
        
        layers = []
        input_dim = state_dim
        
        for hidden_dim in hidden_dims:
            layers.append(nn.Linear(input_dim, hidden_dim))
            layers.append(nn.ReLU())
            layers.append(nn.Dropout(0.2))
            input_dim = hidden_dim
        
        layers.append(nn.Linear(input_dim, action_dim))
        
        self.network = nn.Sequential(*layers)
    
    def forward(self, x):
        return self.network(x)


class ReplayBuffer:
    """
    Experience replay buffer for DQN training
    Stores (state, action, reward, next_state, done) tuples
    """
    
    def __init__(self, capacity: int = 10000):
        self.buffer = deque(maxlen=capacity)
    
    def push(self, state, action, reward, next_state, done):
        self.buffer.append((state, action, reward, next_state, done))
    
    def sample(self, batch_size: int):
        batch = random.sample(self.buffer, batch_size)
        states, actions, rewards, next_states, dones = zip(*batch)
        return (
            np.array(states),
            np.array(actions),
            np.array(rewards),
            np.array(next_states),
            np.array(dones)
        )
    
    def __len__(self):
        return len(self.buffer)


class HealthDQNAgent:
    """
    DQN Agent for health coaching
    
    NEW ARCHITECTURE:
    - State space: Binary condition features from Random Forest
    - Action space: T5-generated actions (NOT predefined)
    - Each condition -> T5 generates action -> DQN learns Q-values
    """
    
    def __init__(
        self,
        state_dim: int,
        action_dim: int = None,
        action_names: List[str] = None,
        learning_rate: float = 1e-4,
        gamma: float = 0.99,
        epsilon_start: float = 1.0,
        epsilon_end: float = 0.01,
        epsilon_decay: int = 5000,
        buffer_size: int = 10000,
        batch_size: int = 64,
        target_update_freq: int = 100,
        device: str = None,
        use_t5_actions: bool = True
    ):
        """
        Args:
            state_dim: Dimension of state (number of RF conditions)
            action_dim: Number of discrete actions (if use_t5_actions=False)
            action_names: Human-readable action names (if use_t5_actions=False)
            learning_rate: Learning rate for optimizer
            gamma: Discount factor
            epsilon_start: Initial exploration rate
            epsilon_end: Final exploration rate
            epsilon_decay: Steps to decay epsilon
            buffer_size: Replay buffer capacity
            batch_size: Training batch size
            target_update_freq: Steps between target network updates
            device: 'cuda' or 'cpu'
            use_t5_actions: If True, actions are generated by T5 (dynamic action space)
        """
        self.state_dim = state_dim
        self.use_t5_actions = use_t5_actions
        
        # Dynamic action space from rule-based generation
        if use_t5_actions:
            self.action_dim = None  # Will be set dynamically
            self.action_names = []  # Will be populated from rule-based actions
            self.action_to_idx = {}  # Map action text to index
            self.idx_to_action = {}  # Map index to action text
        else:
            self.action_dim = action_dim
            self.action_names = action_names if action_names else []
        
        self.gamma = gamma
        self.batch_size = batch_size
        self.target_update_freq = target_update_freq
        
        # Device
        if device is None:
            self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        else:
            self.device = torch.device(device)
        
        print(f"Using device: {self.device}")
        
        # Q-networks (initialize with dummy action_dim if using T5)
        initial_action_dim = action_dim if action_dim else 10  # Start with 10, will grow
        self.policy_net = DQNNetwork(state_dim, initial_action_dim).to(self.device)
        self.target_net = DQNNetwork(state_dim, initial_action_dim).to(self.device)
        self.target_net.load_state_dict(self.policy_net.state_dict())
        self.target_net.eval()
        
        # Optimizer
        self.optimizer = optim.Adam(self.policy_net.parameters(), lr=learning_rate)
        self.loss_fn = nn.SmoothL1Loss()  # Huber loss
        
        # Replay buffer
        self.memory = ReplayBuffer(buffer_size)
        
        # Epsilon-greedy exploration
        self.epsilon_start = epsilon_start
        self.epsilon_end = epsilon_end
        self.epsilon_decay = epsilon_decay
        self.steps_done = 0
        
        # Training stats
        self.training_step = 0
        self.losses = []
        self.rewards = []
    
    def get_epsilon(self) -> float:
        """
        Exponential decay of epsilon
        """
        epsilon = self.epsilon_end + (self.epsilon_start - self.epsilon_end) * \
                  np.exp(-self.steps_done / self.epsilon_decay)
        return epsilon
    
    def select_action(self, state: np.ndarray, epsilon: float = None) -> int:
        """
        Select action using epsilon-greedy policy
        
        Args:
            state: Current state (condition features)
            epsilon: Exploration rate (if None, uses schedule)
        
        Returns:
            action: Action index
        """
        if epsilon is None:
            epsilon = self.get_epsilon()
        
        self.steps_done += 1
        
        # Epsilon-greedy
        if random.random() < epsilon:
            # Random action (exploration)
            action = random.randrange(self.action_dim)
        else:
            # Greedy action (exploitation)
            with torch.no_grad():
                state_tensor = torch.FloatTensor(state).unsqueeze(0).to(self.device)
                q_values = self.policy_net(state_tensor)
                action = q_values.argmax().item()
        
        return action
    
    def store_transition(self, state, action, reward, next_state, done):
        """
        Store transition in replay buffer
        """
        self.memory.push(state, action, reward, next_state, done)
    
    def train_step(self):
        """
        Perform one training step
        Sample batch from replay buffer and update Q-network
        """
        if len(self.memory) < self.batch_size:
            return None
        
        # Sample batch
        states, actions, rewards, next_states, dones = self.memory.sample(self.batch_size)
        
        # Convert to tensors
        states = torch.FloatTensor(states).to(self.device)
        actions = torch.LongTensor(actions).to(self.device)
        rewards = torch.FloatTensor(rewards).to(self.device)
        next_states = torch.FloatTensor(next_states).to(self.device)
        dones = torch.FloatTensor(dones).to(self.device)
        
        # Current Q-values
        current_q_values = self.policy_net(states).gather(1, actions.unsqueeze(1)).squeeze(1)
        
        # Target Q-values (Double DQN)
        with torch.no_grad():
            # Select best actions using policy network
            next_actions = self.policy_net(next_states).argmax(1)
            # Evaluate using target network
            next_q_values = self.target_net(next_states).gather(1, next_actions.unsqueeze(1)).squeeze(1)
            target_q_values = rewards + self.gamma * next_q_values * (1 - dones)
        
        # Compute loss
        loss = self.loss_fn(current_q_values, target_q_values)
        
        # Optimize
        self.optimizer.zero_grad()
        loss.backward()
        # Gradient clipping
        torch.nn.utils.clip_grad_norm_(self.policy_net.parameters(), 1.0)
        self.optimizer.step()
        
        # Update target network
        self.training_step += 1
        if self.training_step % self.target_update_freq == 0:
            self.target_net.load_state_dict(self.policy_net.state_dict())
        
        # Record loss
        self.losses.append(loss.item())
        
        return loss.item()
    
    def add_t5_action(self, action_text: str) -> int:
        """
        Add a new rule-based action to the action space
        
        Args:
            action_text: Action description from rule-based generation
        
        Returns:
            Action index
        """
        if action_text in self.action_to_idx:
            return self.action_to_idx[action_text]
        
        # New action - add to mappings
        action_idx = len(self.action_names)
        self.action_names.append(action_text)
        self.action_to_idx[action_text] = action_idx
        self.idx_to_action[action_idx] = action_text
        
        # Update action_dim
        self.action_dim = len(self.action_names)
        
        # Expand network if needed
        if self.action_dim > self.policy_net.network[-1].out_features:
            self._expand_networks()
        
        return action_idx
    
    def _expand_networks(self):
        """
        Expand Q-networks to accommodate more actions
        """
        # Expand by 10 actions at a time to reduce frequent resizing
        new_action_dim = self.action_dim + 10
        
        # Create new networks
        new_policy_net = DQNNetwork(self.state_dim, new_action_dim).to(self.device)
        new_target_net = DQNNetwork(self.state_dim, new_action_dim).to(self.device)
        
        # Copy old weights from final layer
        old_action_dim = self.policy_net.network[-1].out_features
        new_policy_net.network[-1].weight.data[:old_action_dim] = self.policy_net.network[-1].weight.data
        new_policy_net.network[-1].bias.data[:old_action_dim] = self.policy_net.network[-1].bias.data
        
        new_target_net.network[-1].weight.data[:old_action_dim] = self.target_net.network[-1].weight.data
        new_target_net.network[-1].bias.data[:old_action_dim] = self.target_net.network[-1].bias.data
        
        # Copy all other layers (only Linear layers have weights)
        for i in range(len(self.policy_net.network) - 1):
            if hasattr(self.policy_net.network[i], 'weight'):
                new_policy_net.network[i].weight.data = self.policy_net.network[i].weight.data.clone()
                new_policy_net.network[i].bias.data = self.policy_net.network[i].bias.data.clone()
                
                new_target_net.network[i].weight.data = self.target_net.network[i].weight.data.clone()
                new_target_net.network[i].bias.data = self.target_net.network[i].bias.data.clone()
        
        # Replace networks
        self.policy_net = new_policy_net
        self.target_net = new_target_net
        
        # Update optimizer
        self.optimizer = optim.Adam(self.policy_net.parameters(), lr=self.optimizer.param_groups[0]['lr'])
        
        print(f"✓ Expanded action space: {old_action_dim} -> {new_action_dim}")
    
    def get_action_name(self, action: int) -> str:
        """
        Convert action index to human-readable name
        """
        if self.use_t5_actions:
            return self.idx_to_action.get(action, f"Unknown action {action}")
        else:
            return self.action_names[action] if action < len(self.action_names) else f"Action {action}"
    
    def save(self, filepath: str):
        """
        Save model checkpoint
        """
        torch.save({
            'policy_net': self.policy_net.state_dict(),
            'target_net': self.target_net.state_dict(),
            'optimizer': self.optimizer.state_dict(),
            'steps_done': self.steps_done,
            'training_step': self.training_step,
            'losses': self.losses,
            'rewards': self.rewards
        }, filepath)
        print(f"✓ Model saved to {filepath}")
    
    def load(self, filepath: str):
        """
        Load model checkpoint
        """
        checkpoint = torch.load(filepath, map_location=self.device)
        self.policy_net.load_state_dict(checkpoint['policy_net'])
        self.target_net.load_state_dict(checkpoint['target_net'])
        self.optimizer.load_state_dict(checkpoint['optimizer'])
        self.steps_done = checkpoint['steps_done']
        self.training_step = checkpoint['training_step']
        self.losses = checkpoint['losses']
        self.rewards = checkpoint['rewards']
        print(f"✓ Model loaded from {filepath}")


def define_action_space() -> Tuple[List[str], List[str]]:
    """
    Define discrete action space for health coaching
    
    Returns:
        action_names: List of action identifiers
        action_descriptions: List of human-readable descriptions
    """
    action_names = [
        'MAINTAIN',           # Continue current routine
        'INCREASE_STEPS_SMALL',  # Add 1000-2000 steps
        'INCREASE_STEPS_LARGE',  # Add 3000-5000 steps
        'INCREASE_ACTIVITY_LIGHT',  # Add 10-20 min light activity
        'INCREASE_ACTIVITY_MODERATE',  # Add 10-20 min moderate activity
        'INCREASE_ACTIVITY_INTENSE',  # Add 10-20 min intense activity
        'REDUCE_SEDENTARY_SMALL',  # Reduce 30-60 min sedentary
        'REDUCE_SEDENTARY_LARGE',  # Reduce 60-120 min sedentary
        'IMPROVE_SLEEP_DURATION',  # Add 0.5-1 hour sleep
        'IMPROVE_SLEEP_QUALITY',  # Focus on sleep quality
        'BALANCE_NUTRITION',  # Improve diet
        'REST_RECOVERY',  # Rest day (reduce activity)
    ]
    
    action_descriptions = [
        "Maintain your current routine - you're doing well",
        "Add 1,000-2,000 more steps to your daily activity",
        "Significantly increase steps by 3,000-5,000",
        "Add 10-20 minutes of light activity (walking, stretching)",
        "Add 10-20 minutes of moderate activity (brisk walk, cycling)",
        "Add 10-20 minutes of intense activity (running, HIIT)",
        "Reduce sedentary time by 30-60 minutes (take breaks)",
        "Significantly reduce sedentary time by 60-120 minutes",
        "Try to sleep 0.5-1 hour more tonight",
        "Focus on improving sleep quality (consistent schedule, no screens)",
        "Balance your nutrition (more vegetables, less processed food)",
        "Take a rest day to recover (light activity only)",
    ]
    
    return action_names, action_descriptions


if __name__ == "__main__":
    # Example usage
    print("Initializing DQN Agent...")
    
    # Define action space
    action_names, action_descriptions = define_action_space()
    
    # Create agent (assuming 100 conditions from RF)
    agent = HealthDQNAgent(
        state_dim=100,  # Number of conditions from RF
        action_dim=len(action_names),
        action_names=action_names,
        learning_rate=1e-4,
        gamma=0.99,
        epsilon_start=1.0,
        epsilon_end=0.01,
        epsilon_decay=5000,
        buffer_size=10000,
        batch_size=64
    )
    
    print(f"\nAgent initialized:")
    print(f"  - State dim: {agent.state_dim}")
    print(f"  - Action dim: {agent.action_dim}")
    print(f"  - Device: {agent.device}")
    
    # Example: Random state
    example_state = np.random.randint(0, 2, size=100).astype(np.float32)
    
    # Select action
    action = agent.select_action(example_state, epsilon=0.1)
    print(f"\nExample action selection:")
    print(f"  - Action index: {action}")
    print(f"  - Action name: {agent.get_action_name(action)}")
    print(f"  - Description: {action_descriptions[action]}")
    
    # Store transition
    reward = 10.5
    next_state = np.random.binomial(1, 0.5, size=100).astype(np.float32)
    done = False
    
    agent.store_transition(example_state, action, reward, next_state, done)
    
    print(f"\nReplay buffer size: {len(agent.memory)}")
